<?php

return [
    'API_SUCCESS'=>200,
    'API_LOGIN_SUCCESS'=>100,
    'API_LOGIN_FAILED'=>1,
    'API_VALIDATION_FAILED'=>2,
    'API_TOKEN_VALIDATION'=>3,
    'API_USERGROUPLIST_SUCCESS'=>4,
    'API_USER_ADD_SUCCESS'=>5,
    'API_USER_ADD_FAILED'=>6,
    'API_USER_LIST_FAILED'=>7,
    'FILE_WRITE_ERROR'=>8,

];
